---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/:id/posts":
    get:
      summary: Retrieves all posts
      tags:
      - Posts
      responses:
        '200':
          description: posts found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - title
                - text
                - created_at
                - updated_at
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
